
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xcc,\xd1v\x95\x0e},C\xac\x98K\xb5^\x06\xf6'
    
_lr_action_items = {'FUNCTION':([2,12,13,23,],[6,6,6,6,]),'STRING':([2,12,13,23,],[7,7,7,7,]),')':([7,8,9,10,12,16,17,18,20,21,22,26,28,30,],[-10,-16,-9,-8,17,22,-14,-12,24,-6,-13,-11,-5,-7,]),'VARNAME':([0,1,2,3,5,7,8,9,10,11,12,13,14,15,17,19,22,23,25,27,29,30,],[4,-15,10,-2,4,-10,-16,-9,-8,-3,10,10,-1,21,-14,-4,-13,10,28,4,4,-7,]),'=':([4,],[13,]),'NUMBER':([2,12,13,23,],[9,9,9,9,]),',':([7,8,9,10,16,17,18,20,21,22,26,28,30,],[-10,-16,-9,-8,23,-14,-12,25,-6,-13,-11,-5,-7,]),'(':([4,6,10,],[12,15,12,]),'PRINT':([0,1,3,5,7,8,9,10,11,14,17,19,22,27,29,30,],[2,-15,-2,2,-10,-16,-9,-8,-3,-1,-14,-4,-13,2,2,-7,]),'{':([24,],[27,]),'}':([1,3,7,8,9,10,11,14,17,19,22,29,30,],[-15,-2,-10,-16,-9,-8,-3,-1,-14,-4,-13,30,-7,]),'$end':([1,3,5,7,8,9,10,11,14,17,19,22,30,],[-15,-2,0,-10,-16,-9,-8,-3,-1,-14,-4,-13,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'func_params':([15,],[20,]),'func_args':([12,],[16,]),'execute_fn':([0,2,5,12,13,23,27,29,],[1,8,1,8,8,8,1,1,]),'statement':([0,5,27,29,],[3,14,3,14,]),'statement_list':([0,27,],[5,29,]),'expression':([2,12,13,23,],[11,18,19,26,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement_list","S'",1,None,None,None),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','/Users/eli/dev/facts/lang/plyer.py',78),
  ('statement_list -> statement','statement_list',1,'p_statement_list','/Users/eli/dev/facts/lang/plyer.py',79),
  ('statement -> PRINT expression','statement',2,'p_statement_print','/Users/eli/dev/facts/lang/plyer.py',83),
  ('statement -> VARNAME = expression','statement',3,'p_statement_assign','/Users/eli/dev/facts/lang/plyer.py',88),
  ('func_params -> func_params , VARNAME','func_params',3,'p_func_params','/Users/eli/dev/facts/lang/plyer.py',92),
  ('func_params -> VARNAME','func_params',1,'p_func_params','/Users/eli/dev/facts/lang/plyer.py',93),
  ('expression -> FUNCTION ( func_params ) { statement_list }','expression',7,'p_expression_function_def','/Users/eli/dev/facts/lang/plyer.py',98),
  ('expression -> VARNAME','expression',1,'p_expression_varname','/Users/eli/dev/facts/lang/plyer.py',102),
  ('expression -> NUMBER','expression',1,'p_expression_number','/Users/eli/dev/facts/lang/plyer.py',106),
  ('expression -> STRING','expression',1,'p_expression_string','/Users/eli/dev/facts/lang/plyer.py',110),
  ('func_args -> func_args , expression','func_args',3,'p_func_args','/Users/eli/dev/facts/lang/plyer.py',115),
  ('func_args -> expression','func_args',1,'p_func_args','/Users/eli/dev/facts/lang/plyer.py',116),
  ('execute_fn -> VARNAME ( func_args )','execute_fn',4,'p_execute_fn_with_args','/Users/eli/dev/facts/lang/plyer.py',121),
  ('execute_fn -> VARNAME ( )','execute_fn',3,'p_execute_fn_no_args','/Users/eli/dev/facts/lang/plyer.py',125),
  ('statement -> execute_fn','statement',1,'p_statement_execute_fn','/Users/eli/dev/facts/lang/plyer.py',129),
  ('expression -> execute_fn','expression',1,'p_expression_execute_fn','/Users/eli/dev/facts/lang/plyer.py',133),
]
